
[[audio]]
name = "main"
path = "/assets/audio/main.wav"

[[image]]
name = "main"
path = "/assets/img/janell.png"

[[image]]
path = "/assets/img/stars.png"

[[image]]
path = "/assets/img/nature.jpg"


