[[message]]
sender = "Arepo 💖"
relation = "Best Friend"
text = """ Hope you have an amazing day filled with love, laughter, and endless sparkles. 
           You deserve the absolute world! ✨"""
color = "border-aero-pink shadow-aero-pink/20"
gradient = "from-pink-500/20 to-purple-500/20"

