[[scene]]
id = 1
background = "/resources/img/stars.png"
messages = "Welcome to your special birthday space, Janell! 🫧✨"
action = { emoji = "🫧", label = "Teehee" }


[[scene]]
id = 2
background = "/resources/img/stars.png"
messages =  "I built this little visual universe just for you to celebrate your warmth, kindness, and beauty."
action = { emoji = "🫧", label = "Teehee" }


[[scene]]
id = 3
background = "/resources/img/stars.png"
messages =   "Let the music play, breathe in the good vibes, and pop this bubble to reveal your gift! 💖"
action = { emoji = "🫧", label = "Teehee" }
